path:
  src_dir: '/data/nmaruani/DATASETS/Thingi32_normalized/'
  out_dir: './out/quadrics_thingi_{}/'
io:
  normalize: 'NDC'
  out_poisson: True
  out_pt: True
  out_rvd: False
  out_min_cut: True
  sample_n_base: 100000
model:
  n_points: None
  init: None
optim:
  device: cuda
  lr_base: .001
  repulsion_fac: 0
  sample_fac: .1
  epochs: 400